package basic_demo;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Optional;

import static org.junit.Assert.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class AppTest {


@Test
public void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
}
}