pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                echo 'Checking out...'
                git branch: 'main', url: 'https://github.com/Joao-Vieira-1231835/devops-23-24-JPE-JPM-1231835.git'
            }
        }
        stage('Prepare') {
            steps {
                echo 'Setting executable permissions for gradlew...'
                script {
                    if (isUnix()) {
                        dir('CA2/Part2/react-and-spring-data-rest-basic') {
                            sh 'chmod +x gradlew'
                        }
                    } else {
                        echo 'Skipping chmod on Windows'
                    }
                }
            }
        }
        stage ('Assemble') {
            steps {
                echo 'Assembling CA2/Part2/react-and-spring-data-rest-basic project...'
                script {
                    if (isUnix()) {
                        dir ('CA2/Part2/react-and-spring-data-rest-basic') {
                            sh './gradlew clean'
                            sh './gradlew assemble'
                        }
                    } else {
                        dir ('CA2/Part2/react-and-spring-data-rest-basic') {
                            bat 'gradlew.bat clean'
                            bat 'gradlew.bat assemble'
                        }
                    }
                }
            }
        }
        stage ('Test') {
            steps {
                echo 'Running tests...'
                script {
                    if (isUnix()) {
                        dir('CA2/Part2/react-and-spring-data-rest-basic') {
                            sh './gradlew test'
                        }
                    } else {
                        dir('CA2/Part2/react-and-spring-data-rest-basic') {
                            bat 'gradlew.bat test'
                        }
                    }
                }
            }
            post {
                always {
                    echo 'Publishing test results...'
                    junit 'CA2/Part2/react-and-spring-data-rest-basic/build/test-results/test/*.xml'
                }
            }
        }
        stage ('Javadoc') {
            steps {
                echo 'Generating Javadoc...'
                script {
                    if (isUnix()) {
                        dir('CA2/Part2/react-and-spring-data-rest-basic') {
                            sh './gradlew javadoc'
                        }
                    } else {
                        dir('CA2/Part2/react-and-spring-data-rest-basic') {
                            bat 'gradlew.bat javadoc'
                        }
                    }
                }
                echo 'Archiving and publishing Javadoc...'
                publishHTML(target: [allowMissing: false,
                                     alwaysLinkToLastBuild: false,
                                     keepAll: true,
                                     reportDir: '/var/jenkins_home/workspace/CA5-2/CA2/Part2/react-and-spring-data-rest-basic/build/docs/javadoc',
                                     reportFiles: 'index.html',
                                     reportName: 'Javadoc Report'])
            }
        }
        stage ('Archiving') {
            steps {
                echo 'Archiving...'
                archiveArtifacts 'CA2/Part2/react-and-spring-data-rest-basic/build/libs/*.war'
            }
        }
        stage('Docker') {
            steps {
                script {
                    echo 'Building and publishing Docker image...'
                    def dockerImage = docker.build("joaoa/react-and-spring-data-rest-basic:${env.BUILD_ID}", "-f ./ca5/Dockerfile .")
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-id') {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}