package basic_demo;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.Test;

import java.util.Optional;

import static org.junit.Assert.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class AppTest {


@Test
public void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(Optional.of("app should have a greeting"), classUnderTest.getGreeting());
}
}