pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                echo 'Checking out...'
                git branch: 'main', url: 'https://github.com/Joao-Vieira-1231835/devops-23-24-JPE-JPM-1231835.git'
            }
        }
        stage('Prepare') {
            steps {
                echo 'Setting executable permissions for gradlew...'
                script {
                    if (isUnix()) {
                        dir('CA2/Part1') {
                            sh 'chmod +x gradlew'
                        }
                    } else {
                        echo 'Skipping chmod on Windows'
                    }
                }
            }
        }
        stage ('Assemble') {
            steps {
                echo 'Assembling CA2/Part1 project...'
                script {
                    if (isUnix()) {
                        dir ('CA2/Part1') {
                        sh 'ls -la'
                            sh './gradlew clean'
                            sh './gradlew assemble'
                        }
                    } else {
                        dir ('CA2/Part1') {
                            bat 'gradlew.bat clean'
                            bat 'gradlew.bat assemble'
                        }
                    }
                }
            }
        }
        stage ('Test') {
            steps {
                echo 'Running tests...'
                script {
                    if (isUnix()) {
                        dir('CA2/Part1') {
                            sh './gradlew test'
                        }
                    } else {
                        dir('CA2/Part1') {
                            bat 'gradlew.bat test'
                        }
                    }
                }
            }
            post {
                always {
                    echo 'Publishing test results...'
                    junit 'CA2/Part1/build/test-results/test/*.xml'
                }
            }
        }
        stage ('Archiving') {
            steps {
                echo 'Archiving...'
                archiveArtifacts 'CA2/Part1/build/libs/*.jar'
            }
        }
    }
}
